# Generated by Django 4.1.4 on 2023-02-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
        ('base', '0006_alter_user_avatar'),
    ]

    operations = [
    ]
